In [8]:
alist = [3, 11, 1, 5, 13, 7, 8, 9]


In [ ]:
print(alist)


[3, 11, 1, 5, 13, 7, 8, 9]


In [ ]:
# Prints 8 to console, works backwards
alist[-2]

8

In [ ]:
# Slicing - up to but not the last number in the call
# prints [1, 5, 13] to console
alist[2:5]

[1, 5, 13]

In [ ]:

alist[2:]

[1, 5, 13, 7, 8, 9]

In [ ]:
print(*alist)

3 11 5 13 7 8 9


In [ ]:
alist[2:3] = []
print(*alist)

3 11 5 13 7 8 9


In [ ]:
# Prints 0-6 to console
for i in range(7):
  print(i)

0
1
2
3
4
5
6


In [11]:
# check for even or odd check
for x in alist:
  if x % 2 == 0:
    print(x, "even")
  else:
    print(x, "Odd")


3 Odd
11 Odd
1 Odd
5 Odd
13 Odd
7 Odd
8 even
9 Odd


In [12]:
# Simple even or odd check
for x in alist:
  check = x , 'even' if (x % 2 == 0) else 'odd'
  print(check)

# Function w/ Boolean check for even or odd.
def even_or_odd(x):
  for x in alist:
    result = x, True if (x % 2 == 0) else False
    print(result)


even_or_odd(alist)





(3, 'odd')
(11, 'odd')
(1, 'odd')
(5, 'odd')
(13, 'odd')
(7, 'odd')
(8, 'even')
(9, 'odd')
(3, False)
(11, False)
(1, False)
(5, False)
(13, False)
(7, False)
(8, True)
(9, False)


In [ ]:
squares = []
for x in range(10):
  squares.append(x**2) # Power of Two
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [13]:
# List Comprehensions
# Go over printing only odds and even.
squares = [(x**2) for x in range(10)]
print(squares)




[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [14]:
import numpy as np

C = np.array ([[2,5,1],
              [4,10,2],
              [-3,5,11]])
print(C)
C[1][-2]



[[ 2  5  1]
 [ 4 10  2]
 [-3  5 11]]


array([ 4, 10,  2])

In [15]:
# Print only [4 10] using slicing

C[1, :2]


array([ 4, 10])

In [4]:
C[1, 0:2]

array([ 4, 10])

In [16]:
C[1:, 0:2]

array([[ 4, 10],
       [-3,  5]])

In [ ]:
C > 2

array([[False,  True, False],
       [ True,  True, False],
       [False,  True,  True]])

In [ ]:
C[C > 2]

array([ 5,  4, 10,  5, 11])

In [5]:
# 1-D array = Vector
# 2-D array = Matrix
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]
              ])

v = np.array([[1,0,1]])

y = np.empty_like(x)

for i in range(4):
  y[i] = x[i] + v

print(y)





[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
x + v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [ ]:
np.sum(x, axis = 0)

array([26, 26, 34])

In [ ]:
import matplotlib.pyplot as plt