---
# **Lists**
---


\

## i. Syntax For List Comprehension

---

> list = [EXPRESSION for ITEM in ITERABLE if CONDITION == TRUE]

---




In [ ]:
import numpy as np

list = [3, 11, 1, 5, 13, 7, 8, 9]

list_2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


# Prints list as is w/ brackets & commas
print(list, '\n')


# Prints list w/o brackets & commas
print(*list, '\n')


print('list[2:] = ', list[2:], '\n')

print('list[:4] = ', list[:4], '\n')


# Prints the call of the index to console with the actual indexed number
print('list[-2] = ', list[-2], '\n')


# Prints the numbers in the list from index [0] = 3 up to [:-2] = 7
print('list[:-2] = ', list[:-2], '\n')


# Prints the numbers in the list from index [-4] = 13 onwards till list ends
print('list[-4:] = ', list[-4:], '\n')


# Prints a sub-set of our list from index [3:6] = 5 to 7 *NOT including I[6]
print('Subset of list: ', list[3:6], '\n')


# Removing a section of a list. Using 0-9 to better understand conceptually

print('A new list before removing a section: \n', list_2, '\n')
list_2[3:6] = []
print('After Removing Index [3:6]: \n', list_2, '\n')




# Function that breaks up a list by each Index and its respective #
def index_function(x):
  i = 0
  j = 0
  while i < len(list):
    print('Index [{}]:'.format(i), [list[j]],)
    i += 1
    j += 1


# Testing Indexing function
index_function(list)

# Another way to show Index and its respective #
for x in enumerate(list):
  print(x)



list_2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Function to square all the numbers in a list
# Parameter 'x'
# Argument 'list_2

def square_A_list(x):
  squares = []
  for num in x:
    squares.append(num**2)
  return squares

square_A_list(list_2)


[3, 11, 1, 5, 13, 7, 8, 9] 

3 11 1 5 13 7 8 9 

list[2:] =  [1, 5, 13, 7, 8, 9] 

list[:4] =  [3, 11, 1, 5] 

list[-2] =  8 

list[:-2] =  [3, 11, 1, 5, 13, 7] 

list[-4:] =  [13, 7, 8, 9] 

Subset of list:  [5, 13, 7] 

A new list before removing a section: 
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 

After Removing Index [3:6]: 
 [0, 1, 2, 6, 7, 8, 9] 

Index [0]: [3]
Index [1]: [11]
Index [2]: [1]
Index [3]: [5]
Index [4]: [13]
Index [5]: [7]
Index [6]: [8]
Index [7]: [9]
(0, 3)
(1, 11)
(2, 1)
(3, 5)
(4, 13)
(5, 7)
(6, 8)
(7, 9)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
# Syntax for List Comprehension:
# list = [EXPRESSION for ITEM in ITERABLE if CONDITION == TRUE]

squares = [x ** 2 for x in list_2]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


---
# Numpy Section
---

i.) import numpy as np

In [ ]:
import numpy as np

a = np.array([[3,1,6,2,2,7,7],[1,5,5,2,1,5,7]])

# Outputs each dimension of the array on individual lines
print('Array a is: ', *a, sep='\n')

# 2 rows and 7 columns
print('the shape of a is', a.shape[0], 'rows and', a.shape[1], 'columns')

# Outputs: 4 6 11 4 3 12 14
print('sum of a per column: ', *np.sum(a, axis=0))

# Outputs: 28 26
print('sum of a per row: ', *a.sum(axis=1))

Array a is: 
[3 1 6 2 2 7 7]
[1 5 5 2 1 5 7]
the shape of a is 2 rows and 7 columns
sum of a per column:  4 6 11 4 3 12 14
sum of a per row:  28 26


# Broadcasting
---

In [ ]:
x = np.array([[13,5,2], [7,14,9], [1, 11, 2]])
w = np.array([1, 2, 1])
y = x - w
print(y)


[[12  3  1]
 [ 6 12  8]
 [ 0  9  1]]


---
# Sum Of Squared Differences
---

In [ ]:
import numpy as np


def sumOfSquaredDifferences(arr):
    N = len(arr)
    sum = 0

    # Nested loops to generate all possible pairs
    for i in range(N):
        for j in range(i + 1, N):
            # Calculating the square of the difference between the pairs
            diff = arr[i] - arr[j]
            sum += (diff * diff)

    # Output the sum of squared differences of all possible pairs
    print(sum)





x = [2,8,4]
sumOfSquaredDifferences(x)

56


---
#Assignment To Practice
---

In [ ]:
import numpy as np

# Define the arrays
C = np.array([
    [2, 5, 1],
    [4, 10, 2],
    [0, 5, 11],
    [1, 2, 100],
    [0, 15, 1]])

lbl = np.array([2, 1, 2, 1, 1])

# Create a boolean mask where lbl == 1
mask = lbl == 1

# Use the mask to filter C
result = C[mask]

print(result)

'''
1. import numpy as np
   This line imports the NumPy library and gives it the alias 'np',
   allowing us to use NumPy functions with the prefix 'np'.

2. C = np.array([...])` and `lbl = np.array([...])
   These lines create NumPy arrays from the given lists.
   C is a 5x3 array, and lbl is a 1D array with 5 elements.

3. mask = lbl == 1
   This line creates a boolean mask. Here's what happens:
   - NumPy compares each element of lbl to the value 1.
   - It returns a new array of the same shape as lbl,
      where each element is True if the corresponding
      element in lbl is 1, and False otherwise.
   - So, mask becomes: [False, True, False, True, True]

4. result = C[mask]
   This is where the filtering happens:
   - NumPy uses the boolean mask to index into C.
   - It selects only the rows of C where the corresponding element in mask is True.
   - In this case, it selects the 2nd, 4th, and 5th rows of C
   (remember, Python uses 0-based indexing).

5. print(result)
   This prints the resulting filtered array.

The key to this operation is NumPy's boolean indexing.
When you use a boolean array to index another array,
NumPy returns only the elements where the boolean array is True.
In this case, we're using it to select entire rows of C based
on the values in lbl.

This method is very efficient because:
1. It avoids explicit loops, using vectorized operations instead.
2. It doesn't require creating a new array manually;
    NumPy handles the creation of the new, filtered array.
3. It's concise and readable, expressing a complex operation
    in a single line of code.

The result is a new array containing only the rows of C where the corresponding
value in lbl is 1, achieving the filtering you requested without using explicit
loops or conditional statements.

'''

[[  4  10   2]
 [  1   2 100]
 [  0  15   1]]


"\n1. import numpy as np\n   This line imports the NumPy library and gives it the alias 'np',\n   allowing us to use NumPy functions with the prefix 'np'.\n\n2. C = np.array([...])` and `lbl = np.array([...])\n   These lines create NumPy arrays from the given lists.\n   C is a 5x3 array, and lbl is a 1D array with 5 elements.\n\n3. mask = lbl == 1\n   This line creates a boolean mask. Here's what happens:\n   - NumPy compares each element of lbl to the value 1.\n   - It returns a new array of the same shape as lbl,\n      where each element is True if the corresponding\n      element in lbl is 1, and False otherwise.\n   - So, mask becomes: [False, True, False, True, True]\n\n4. result = C[mask]\n   This is where the filtering happens:\n   - NumPy uses the boolean mask to index into C.\n   - It selects only the rows of C where the corresponding element in mask is True.\n   - In this case, it selects the 2nd, 4th, and 5th rows of C\n   (remember, Python uses 0-based indexing).\n\n5. pri

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0., 5., .30)

# red dashes, blue squares etc
plt.plot(t, t, '--*r', label='t')
plt.plot(t, t**2, 'bs', label='t^2')
plt.xlabel('t')
plt.ylabel('f(t)')
plt.legend()
plt.title('hello')
plt.show()

In [ ]:
import numpy as np

my_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']


# ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
# [ 0    1    2    3    4    5    6    7    8 ]

# ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
# [-9   -8   -7   -6   -5   -4   -3   -2   -1 ]

print(my_list[5:3:-1])

#my_list[-5:-2]
#my_list[::2]
#my_list[1::2]

#my_list[::-1]
#my_list[5:3:-1]
#my_list[-2:-5:-1]
#my_list[-1:-8:-3]




['f', 'e']


In [1]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6]])
print(array1[0,:])
print(array1[:,0])
print(array1[-1])

[1 2 3]
[1 4]
[4 5 6]
