In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Unmount and flush our google drive when we are all finished with examining.
from google.colab import drive
drive.flush_and_unmount(timeout_ms=24*60*60*100)

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/4.) Clustering Material/clustering_data.csv',header=None)

# the file has no column headers, so add headers
df.columns = ['x1', 'x2']
df.head(10)

x1      x2
0  3.1752  7.8710
1  2.6642  7.6277
2  2.3966  7.1168
3  3.0779  7.0195
4  2.6642  6.5328
5  3.3455  6.5328
6  3.6861  7.1168
7  3.7591  7.7007
8  2.7372  8.2117
9  2.1533  7.8954

In [3]:
data = df.to_numpy()

In [4]:
from sklearn.cluster import KMeans
import numpy as np

k=5 # change this to enter different number of clusters

# call k-means fit() to apply clustering on the data
# https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
kmeans = KMeans(n_clusters=k, random_state=40, n_init="auto").fit(data)

In [5]:
# results: cluster centroids, the centroid for each cluster
kmeans.cluster_centers_

array([[3.98854286, 5.64302857],
       [6.63423333, 3.1914    ],
       [2.86582857, 7.69724286],
       [7.31955   , 2.44526667],
       [3.15572   , 6.69342   ]])

In [ ]:
# cluster labels assigned to each point in the data
kmeans.labels_

array([2, 2, 2, 4, 4, 4, 4, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1,
       1, 3, 4, 1, 3, 3, 3, 3, 3], dtype=int32)

In [ ]:
# clustering metrics
# there are many e.g. I am using silhouette score
# https://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation
from sklearn import metrics
from sklearn.metrics import pairwise_distances
metrics.silhouette_score(data, kmeans.labels_, metric='euclidean')

0.35298073141580105

In [ ]:
# total SSE[Sum-Squared-Error], over ALL the clusters and data points, they call it inertia
kmeans.inertia_

8.557531420523812

In [ ]:
# SSE[Sum-Squared-Error] in EACH of the k clusters
# this is not code you are expected to know how to do on your own in this course
# just as an idea of how to find things (e.g. Google search or use any Gen AI tool)
# from https://stackoverflow.com/questions/66555997/how-to-get-sse-for-each-cluster-in-k-means
clusterwise_sse = np.zeros(k)
for point, label in zip(data, kmeans.labels_):
    clusterwise_sse[label] += np.square(point - kmeans.cluster_centers_[label]).sum()

In [ ]:
clusterwise_sse

array([1.54722389, 1.64705387, 2.50783763, 1.74715337, 1.10826266])